[package]
name = "qos"
version = "0.1.0"
edition = "2024"
build = "compiletime/build.rs"

[dependencies]
fatfs = { default-features = false, features = ["alloc", "lfn"],  git = "https://github.com/rafalh/rust-fatfs" }
hashbrown = "0.15.4"
linked_list_allocator = "0.10.5"
spin = { version = "0.10.0", default-features = false, features = ["spin_mutex"] }

[build-dependencies]
glob = "0.3"
