#ifndef KEY_H
#define KEY_H
#include <types.h>

typedef enum key_modifiers
{
    shift = 0x1,
    ctrl = 0x2,
    alt = 0x4,
    caps = 0x8
} key_modifiers;

// TODO: PrntScrn, Pause
typedef enum key_code
{
    KEY_a, 
    KEY_b,
    KEY_c,
    KEY_d,
    KEY_e,
    KEY_f,
    KEY_g,
    KEY_h,
    KEY_i,
    KEY_j,
    KEY_k,
    KEY_l,
    KEY_m,
    KEY_n,
    KEY_o,
    KEY_p,
    KEY_q,
    KEY_r,
    KEY_s,
    KEY_t,
    KEY_u,
    KEY_v,
    KEY_w,
    KEY_x,
    KEY_y,
    KEY_z,
    KEY_n0,
    KEY_n1,
    KEY_n2,
    KEY_n3,
    KEY_n4,
    KEY_n5,
    KEY_n6,
    KEY_n7,
    KEY_n8,
    KEY_n9,
    KEY_backtick,
    KEY_minus,
    KEY_equals,
    KEY_backslash,
    KEY_backspace,
    KEY_space,
    KEY_tab,
    KEY_caps_lock,
    KEY_lshift,
    KEY_lctrl,
    KEY_lgui,
    KEY_lalt,
    KEY_rshift,
    KEY_rctrl,
    KEY_rgui,
    KEY_ralt,
    KEY_apps,
    KEY_enter,
    KEY_escape,
    KEY_f1,
    KEY_f2,
    KEY_f3,
    KEY_f4,
    KEY_f5,
    KEY_f6,
    KEY_f7,
    KEY_f8,
    KEY_f9,
    KEY_f10,
    KEY_f11,
    KEY_f12,
    KEY_scroll_lock,
    KEY_brackl,
    KEY_insert,
    KEY_home,
    KEY_page_up,
    KEY_del,
    KEY_end,
    KEY_page_down,
    KEY_up_arrow,
    KEY_left_arrow,
    KEY_down_arrow,
    KEY_right_arrow,
    KEY_num_lock,
    KEY_numpad_slash,
    KEY_numpad_asterrisk,
    KEY_numpad_minus,
    KEY_numpad_plus,
    KEY_numpad_enter,
    KEY_numpad_dot,
    KEY_numpad_0,
    KEY_numpad_1,
    KEY_numpad_2,
    KEY_numpad_3,
    KEY_numpad_4,
    KEY_numpad_5,
    KEY_numpad_6,
    KEY_numpad_7,
    KEY_numpad_8,
    KEY_numpad_9,
    KEY_brackr,
    KEY_semicolon,
    KEY_apostrophe,
    KEY_comma,
    KEY_dot,
    KEY_slash,
    KEY_power,
    KEY_sleep,
    KEY_wake,
    KEY_next_track,    
    KEY_previous_track,
    KEY_stop,          
    KEY_play_pause,    
    KEY_mute,          
    KEY_vol_up,     
    KEY_vol_down,   
    KEY_media_select,  
    KEY_email,        
    KEY_calc,    
    KEY_my_computer,   
    KEY_www_search,    
    KEY_www_home,      
    KEY_www_back,      
    KEY_www_forward,   
    KEY_www_stop,      
    KEY_www_refresh,   
    KEY_www_favorites,
    KEY_unknown,
} key_code;

typedef enum key_press_type {
    KEY_release,
    KEY_press
} key_press_type;

typedef struct key {
    u8 scancode;
    key_code key;
    char ascii;
    key_press_type type;
    key_modifiers mods;
} key;

char keycode_to_ascii(key_code code, u8 shift, u8 caps);
#endif